# RequestIdentification.srv
# Service to request identification of a tracked person

# Request
int32 track_id
int32 bbox_x
int32 bbox_y
int32 bbox_w
int32 bbox_h
std_msgs/Header header  # Timestamp from original frame

---

# Response
bool success
string message
